### ISSUE TITLE
Astro doesn't respect vite options

### ISSUE THREAD

**Issue by bautrukevich** [withastro/astro#10452]
### Astro Info

```block
No problem with that
```

### If this issue only occurs in one browser, which browser is a problem?

Doesn't matter

### Describe the Bug

I have a config:

```ts
import { defineConfig } from "astro/config";

// https://astro.build/config
export default defineConfig(() => {
  return {
    vite: {
      css: {
        modules: {
          localsConvention: "camelCase",
        },
      },
    },
  };
});

```

But it's doesn't work. When I use CSS modules like:

`styles.module.css`:
```css
.nav-mobile {
  justify-content: space-between;
  align-items: center;
  align-self: stretch;
  height: 72px;
}

.nav-menu-button {
  color: var(--color-fg-white, #fff);
}
```

And in component:
```jsx
<div class:list={[styles.container, styles.navMobile, styles.mobile]}>
    <div>Logo</div>
    <NavMenuButton class={styles.navMenuButton} />
</div>
```

Astro don't see the `styles.navMobile`, same as `styles.navMenuButton`. Only when using `styles['nav-mobile']` and `styles['nav-menu-button']`.

### What's the expected result?

Astro respect Vite config. Or how to set it correct?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-qaxsjs

### Participation

- [ ] I am willing to submit a pull request for this issue.
