### ISSUE TITLE
:global selector in css nesting

### ISSUE THREAD

**Issue by FrancoJavierGadea** [withastro/astro#10721]
### Astro Info

```block
Astro                    v4.5.16
Node                     v20.11.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/react
```

### This examples work fine

```css
.container {

    & :global(h1) {

        color: #fff;
    }
}

/*Output css*/
.container[data-astro-cid-j7pv25f6] {
    & h1 {
        color: #fff;
    }
}
```

```css
.container {

    & :global(h1) {
        color: #fff;
    }

    span {}
}

/*Output css*/
.container[data-astro-cid-j7pv25f6] {

    & h1 {
        color: #fff
    }

    span {}
}
```
<br>

### This examples not work 

```css
.container {

    :global(h1) {

        color: #fff;
    }
}

/*Output css*/
.container[data-astro-cid-j7pv25f6] {
    :global(h1) {
        color: #fff;
    }
}
```

```css
.container {

    span {}

    & :global(h1) {

        color: #fff;
    }
}

/*Output css*/
.container[data-astro-cid-j7pv25f6] {
    span {}

    & :global(h1) {
        color: #fff;
    }
}
```

### What's the expected result?

```css
.container {

    :global(h1) {

        color: #fff;
    }
}

/*Output css*/
.container[data-astro-cid-j7pv25f6] {
    h1 {
        color: #fff;
    }
}
```

```css
.container {

    span {}

    & :global(h1) {

        color: #fff;
    }
}

/*Output css*/
.container[data-astro-cid-j7pv25f6] {
    span {}

    & h1 {
        color: #fff;
    }
}
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-8wzk1y?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I'm not sure if this is a compiler issue since it may not handle CSS nesting syntax well. This problem should be able to be worked around by setting up `postcss-nesting` or `postcss-nested` in a `postcss.config.cjs` file though.

**Comment by matthewp** [comment]
New reproduction: https://stackblitz.com/edit/withastro-astro-3qrvob?file=src%2Fpages%2Findex.astro

- Discussion: https://github.com/csstools/postcss-plugins/discussions/1474

**Comment by FrancoJavierGadea** [comment]
### New strange behavior:

[Stackblitz link](https://stackblitz.com/edit/withastro-astro-kafk54?file=src%2Fpages%2Findex.astro)

#### Issue:
I'm using CSS nesting in an Astro project, and I've noticed an inconsistency in the scoped styles when using the `&` symbol.

#### Example:
When using the `&` symbol for nesting, the component's scoped styles are correctly applied in the transpiled CSS:

```css
.Container-1 {
    /* Works fine with '&' */
    & p {
        font-size: 22px;
        color: red;
    }
}

/* Resulting CSS */
.Container-1[data-astro-cid-lntfltpf] {
    & p[data-astro-cid-lntfltpf] {
        font-size: 22px;
        color: red;
    }
}
```

However, if I omit the `&` symbol, the scoped style is lost, and the rule behaves as if it's in the global scope:

```css
.Container-2 {
    /* Doesn't work without '&' */
    p {
        font-size: 22px;
        color: red;
    }
}

/* Resulting CSS */
.Container-2[data-astro-cid-c7xfxlmo] {
    p {
        font-size: 22px;
        color: red;
    }
}
```

Astro version: `4.15.12`
