### ISSUE TITLE
MDX Layout css applied after component css on build

### ISSUE THREAD

**Issue by claytercek** [withastro/astro#11040]
### Astro Info

```block
Astro                    v4.7.0
Node                     v20.10.0
System                   macOS (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         @astrojs/react
```

### Describe the Bug

When using the mdx integration, if you specify a layout in the frontmatter, the CSS from that layout will be included _after_ any imported component css when built. 

In the linked stackoverflow, `pages/index.mdx` imports a component (`Demo.astro`) which has some component styles, and has a layout (`RootLayout.astro`) which includes some global styles that specify the layer order with the `@layer` directive.

Here's the relevant css:

```css
/* global styles in RootLayout.astro  */

@layer reset, component;

@layer reset {
    * {
        background: white;
        color: black;
    }
}

/* styles in Demo.astro */

@layer component {
    div {
        background: red;
        color: blue;
    }
}
```

The compiled css ends up looking like this (whitespace added for readability):

```css
@layer component {
    div[data-astro-cid-tb5vpudz] {
        background: red;
        color: #00f
    }
}

@layer reset, component;
@layer reset{
    * {
        background: #fff;
        color: #000
    }
}
```

Because the component layer is declared _before_ the reset layer, the reset layer is taking precedence.

### What's the expected result?

I'd expect the styles from the layout to be included before the styles from any imported components: 

```css
@layer reset, component;
@layer reset{
    * {
        background: #fff;
        color: #000
    }
}

@layer component {
    div[data-astro-cid-tb5vpudz] {
        background: red;
        color: #00f
    }
}
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ceeysf?file=src%2Fcomponents%2FDemo.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.
