### ISSUE TITLE
Optimalization: ViewTransition CSS should be after after `<body>`

### ISSUE THREAD

**Issue by Akxe** [withastro/astro#11460]
### Astro Info

```block
Astro                    v4.11.1
Node                     v20.14.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/sitemap
```

### If this issue only occurs in one browser, which browser is a problem?

All

### Describe the Bug

The first 4578 lines of code are `<head>` (mostly `CSS`). 4573 lines (309525 characters) of that is only Astro transition CSS. Every one of these CSS declarations are the same:

```css
[data-astro-transition-fallback="old"] [data-astro-transition-scope="astro-jnro4gcx-127"],
[data-astro-transition-fallback="old"][data-astro-transition-scope="astro-jnro4gcx-127"] { 
	animation-duration: 180ms;
	animation-timing-function: cubic-bezier(0.76, 0, 0.24, 1);
	animation-fill-mode: both;
	animation-name: astroFadeOut;
}

[data-astro-transition-fallback="new"] [data-astro-transition-scope="astro-jnro4gcx-127"],
[data-astro-transition-fallback="new"][data-astro-transition-scope="astro-jnro4gcx-127"] { 
	animation-duration: 180ms;
	animation-timing-function: cubic-bezier(0.76, 0, 0.24, 1);
	animation-fill-mode: both;
	animation-name: astroFadeIn;
}

[data-astro-transition=back][data-astro-transition-fallback="old"] [data-astro-transition-scope="astro-jnro4gcx-127"],
[data-astro-transition=back][data-astro-transition-fallback="old"][data-astro-transition-scope="astro-jnro4gcx-127"] { 
	animation-duration: 180ms;
	animation-timing-function: cubic-bezier(0.76, 0, 0.24, 1);
	animation-fill-mode: both;
	animation-name: astroFadeOut;
}
[data-astro-transition=back][data-astro-transition-fallback="new"] [data-astro-transition-scope="astro-jnro4gcx-127"],
[data-astro-transition=back][data-astro-transition-fallback="new"][data-astro-transition-scope="astro-jnro4gcx-127"] { 
	animation-duration: 180ms;
	animation-timing-function: cubic-bezier(0.76, 0, 0.24, 1);
	animation-fill-mode: both;
	animation-name: astroFadeIn;
}
```

### What's the expected result?

My suggestion:
Move view transition CSS to the end of `<body>` for earlier HTML parsing

Additional suggestion:
Since every view transition is common to at least 2 pages, wouldn't it be better to reference them as file(s)?

### Link to Minimal Reproducible Example

https://gingerarchitecture.cz/

### Participation

- [ ] I am willing to submit a pull request for this issue.
