### ISSUE TITLE
@astro/mdx rendering backticks when using inline code

### ISSUE THREAD

**Issue by Reeceeboii** [withastro/astro#11594]
### Astro Info

```block
Astro                    v4.12.3
Node                     v20.16.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When embedding a piece of inline code using single backticks, the backticks are rendered in the resulting HTML when I am expecting them not to be.

E.g. I am using `single backticks here`. On my site, this is resulting in `` `single backticks here` `` showing up on the page. My site is based on the [astro-gaia](https://github.com/danielecammarata/astro-gaia) template, which is live as a preview on [Netlify](https://astro-gaia.netlify.app/posts/tech-css-grid/#2-implicit-vs-explicit-grids), and the issue is visible there too.

I am using `"@astrojs/mdx": "^3.1.3"`

.mdx:
![image](https://github.com/user-attachments/assets/df5ba7db-3eb1-4f72-98bd-390f60be8ddd)

Site:
![image](https://github.com/user-attachments/assets/5f130517-5f11-44de-9a89-3db89f2b4747)

### What's the expected result?

The backticks themselves are not rendered.

### Link to Minimal Reproducible Example

https://github.com/danielecammarata/astro-gaia

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ArmandPhilippot** [comment]
This doesn't seem to come from Astro but from the template used. When inspecting the rendered code in the Developer tools (`Ctrl`+`Maj`+`i` in Firefox), you can see that some CSS is applied to the `code` element:

```css
.prose :where(code):not(:where([class~="not-prose"], [class~="not-prose"] *))::before {
  content: "`";
}

.prose :where(code):not(:where([class~="not-prose"], [class~="not-prose"] *))::after {
  content: "`";
}
```

The backticks are added with CSS. You could try to add some custom CSS to override this behavior.
