### ISSUE TITLE
Cloudflare Workers (Beta Assets). Broken Caching `_headers`

### ISSUE THREAD

**Issue by predaytor** [withastro/astro#12139]
### Astro Info

```block
Astro                    v4.15.11
Node                     v22.8.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             astro-robots-txts
```

### Describe the Bug

Using the [experimental](https://developers.cloudflare.com/workers/frameworks/framework-guides/astro/) deployment of Cloudflare Workers for Astro, caching does not seem to work for paths specified in `_headers`.

Response headers for static assets: `cache-control: public, max-age=0, must-revalidate`.

https://my-astro-app.thepredaytor.workers.dev/

`public/_routes.json`:
```json
{
  "version": 1,
  "include": [
    "/*"
  ],
  "exclude": [
    "/_astro/*",
    "/.assetsignore",
    "/favicon.svg"
  ]
}
```
`public/_headers`:
```txt
/_astro/*
  Cache-Control: public, max-age=31557600, immutable

/favicon.ico
  Cache-Control: public, max-age=3600, immutable

/favicon.svg
  Cache-Control: public, max-age=3600, immutable
```
`wrangler.toml`:
```toml
#:schema node_modules/wrangler/config-schema.json
name = "my-astro-app"
compatibility_date = "2024-10-04"
compatibility_flags = ["nodejs_compat_v2"]
main = "./dist/_worker.js"
assets = { directory = "./dist", binding = "ASSETS" }

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[vars]
MY_VARIABLE = "test"
```

### What's the expected result?

Response headers should represent defined ones in `_headers` file from `/public` directory.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/predaytor/astro-cloudflare

### Participation

- [X] I am willing to submit a pull request for this issue.
