### ISSUE TITLE
Content layer schema references randomly break

### ISSUE THREAD

**Issue by cabaucom376** [withastro/astro#12680]
### Astro Info

```block
Astro                    v5.0.3
Node                     v23.3.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/solid-js
```

### Describe the Bug

When editing content files and changing the names of referenced id's a lot occasionally astro will lock up and not allow the site to be built with an error like this:
```
[InvalidContentEntryDataError] features → core/shards data does not match collection schema.
category: Reference to categories invalid. Entry core does not exist.
```
The category `core` has been verified to exist and is defined properly in a yaml file.

./content/categories.yaml:
```yaml
core:
  sequence: 0
  title: Core
editor:
  sequence: 1
  title: Editor
qol:
  sequence: 3
  title: Quality of Life
connectivity:
  sequence: 4
  title: Connectivity
extensibility:
  sequence: 5
  title: Extensibility
intelligence:
  sequence: 6
  title: Intelligence
platforms:
  sequence: 7
  title: Platforms
```
./src/content.config.ts:
```typescript
import { z, defineCollection, reference } from "astro:content";
import { file, glob } from "astro/loaders";

const categories = defineCollection({
  loader: file("content/categories.yaml"),
  schema: z.object({
    sequence: z.number(),
    title: z.string(),
  }),
});

const features = defineCollection({
  loader: glob({ pattern: "**/*.{md, mdx}", base: "content/features" }),
  schema: z.object({
    title: z.string(),
    description: z.string().optional(),
    sequence: z.number(),
    category: reference("categories"),
    status: z.enum([
      "concept",
      "confirmed",
      "upcoming",
      "development",
      "beta",
      "complete",
    ]),
  }),
});

export const collections = {
  categories: categories,
  features: features,
};
```
./content/features/core/shards.md:
```markdown
---
title: "Shards"
description: "..."
sequence: 0
category: core
status: "development"
---
```

This is really hard to reproduce, but it has happened to me twice now in the last 3 days after my V5 migration, once initially while setting up the glob and file loaders, and another while simply modifying the names of categories. When these instances occur, not even reverting the project back to a time it was functional via git allows for it to build. The only solution I have found after many hours of nothing was this:
1. Comment out the problem schema field, ex: `category: reference("categories"),`
2. Run astro dev, and it should build fine
3. Quit the run
4. Uncomment out the same field
5. Run astro dev again

I feel this is a bug because nothing is changing at all about the schema, yet it can go from not building at all to building perfectly fine.

### What's the expected result?

The website should build and not get locked up randomly on reference data updates.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-chwz8xrn?file=src%2Fcontent.config.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.
