### ISSUE TITLE
GitHub CI error `The requested module '@astrojs/markdown-remark' does not provide an export named 'isFrontmatterValid'`

### ISSUE THREAD

**Issue by hrastnik** [withastro/astro#12844]
### Astro Info

```block
Astro                    v5.1.1
Node                     v20.14.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/sitemap
                         @astrojs/mdx
                         @astrojs/partytown
```

### Describe the Bug

When generating static routes in a GitHub action, i get this error:

```
The requested module '@astrojs/markdown-remark' does not provide an export named 'isFrontmatterValid'
```

The github action does the following

```
      - uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Cache node_modules
        uses: actions/cache@v3
        id: node-modules-cache
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: node-modules-${{ runner.os }}-

      - name: Install node dependencies
        run: pnpm install

      - name: Build with Astro
        run: pnpm build
```

PS. Sorry for not providing a repro example. Here's my package JSON dependencies instead.

```

    "@astrojs/check": "0.9.4",
    "@astrojs/mdx": "4.0.3",
    "@astrojs/partytown": "2.1.2",
    "@astrojs/sitemap": "3.2.1",
    "@astrojs/tailwind": "5.1.4",
    "@astrolib/analytics": "0.6.1",
    "@astrolib/seo": "1.0.0-beta.8",
    "@formatjs/cli": "6.2.10",
    "@formatjs/intl": "2.10.2",
    "@tailwindcss/typography": "0.5.13",
    "@typescript-eslint/eslint-plugin": "7.8.0",
    "@typescript-eslint/parser": "7.8.0",
    "astro": "5.1.1",
    "astro-seo-schema": "5.0.0",
    "axios": "1.7.9",
    "eslint": "8.57.0",
    "eslint-config-prettier": "9.1.0",
    "eslint-plugin-astro": "1.1.2",
    "eslint-plugin-formatjs": "4.13.1",
    "eslint-plugin-import": "2.29.1",
    "eslint-plugin-prettier": "5.1.3",
    "openai": "4.42.0",
    "prettier": "3.2.5",
    "prettier-plugin-astro": "0.13.0",
    "prettier-plugin-tailwindcss": "0.5.14",
    "schema-dts": "1.1.2",
    "sharp": "0.33.3",
    "tailwindcss": "3.4.3",
    "typescript": "5.4.5"
```

### What's the expected result?

I expected the build to go through, and not fail.

### Link to Minimal Reproducible Example

https://stackblitz.com/

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
`isFrontmatterValid` is used in two places

https://github.com/withastro/astro/blob/161df286c3abdbf8c49e8e7de820ce0e36ab5c55/packages/astro/src/vite-plugin-markdown/index.ts#L3-L7

https://github.com/withastro/astro/blob/161df286c3abdbf8c49e8e7de820ce0e36ab5c55/packages/integrations/mdx/src/rehype-apply-frontmatter-export.ts#L3

Astro v5 and `@astrojs/mdx` v4 respectively started using those, which based on your package.json seems already installed. We'd need a repro to dig deeper here.

**Comment by hrastnik** [comment]
I've tried digging deeper and creating a repro, however, I've realized the issue can be fixed by adding this block to the GitHub action yml file.

```yml
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
```

That is, specifying the node version as 20. I think the default version was 18 with the current `ubuntu-latest` image.

The chain of steps now looking like this.

```yml
      - uses: pnpm/action-setup@v4
        name: Install pnpm

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build with Astro
        run: pnpm build
```
