### ISSUE TITLE
🐛 BUG: @media queries in astro files are not well written

### ISSUE THREAD

**Issue by kuworking** [withastro/astro#2123]
### What version of `astro` are you using?

^0.21.9

### What package manager are you using?

npm

### What operating system are you using?

Windows 10

### Describe the Bug

Within a `<style>` tag in an `.astro` file, if I add something like this

```css
<style>
  .parent {
/*... */
    opacity: 1;
    opacity: 0.8;
    @media (min-width: 25em) {
      font-size: 1.7rem;
    }
  }
</style>
```

then I see in the css (Chrome developer tools)

```html
opacity: 0.8;
                @media(min-width: 25em) {
                </style>
                <style global="true" astro-style="true">
                    blockquote {
```

![image](https://user-images.githubusercontent.com/4474004/144705887-b7457efa-5957-44a2-92f7-5c727a5e2121.png)

### Link to Minimal Reproducible Example

https://codesandbox.io/s/goofy-clarke-y1ir9?file=/src/pages/index.astro
