### ISSUE TITLE
🐛 BUG: CSS @keyframes rules prevent scoping for all rules that follow

### ISSUE THREAD

**Issue by tylergaw** [withastro/astro#2127]
### What version of `astro` are you using?

0.21.10

### What package manager are you using?

yarn

### What operating system are you using?

Mac

## Summary

Using `@keyframes` in a `<style>` block in an astro component breaks selector scoping for all rules after the `@keyframes` rule.

This behavior changed between 0.20 and 0.21.

### Example

Is this example, the `.my-para` declaration will be scoped properly. The `.another-para` will not be scoped.

```astro
<style>
  .my-para {
    color: blue;
  }

  @keyframes fadeIn {
    to {
      opacity: 100%;
    }
  }

  .another-para {
    color: red;
  }
</style>
```

That input CSS produces the following bundled CSS. **Note**: I've modified formatting here for readability

```css
.my-para.astro-FNZOVGOV {
  color: #00f;
}
@keyframes fadeIn {
  to {
    opacity: 100%;
  }
}
.another-para {
  color: red;
}
```

The expecation is that `.another-para` would be scoped `.another-para.astro-FNZOVGOV`. This was was the behavior in Astro pre 0.21.

## Further testing

From what I've been able to tell, the `@keyframes` rule breaks scoping for all rules that come after it. So, if we modify our above example to put `@keyframes` first, no styles are scoped

```astro
<style>
  @keyframes fadeIn {
    to {
      opacity: 100%;
    }
  }

  .my-para {
    color: blue;
  }

  .another-para {
    color: red;
  }
</style>
```

produces the following (again, formatting modified here for readability)

```css
@keyframes fadeIn {
  to {
    opacity: 100%;
  }
}
.my-para {
  color: #00f;
}
.another-para {
  color: red;
}
```

## Working around this

This is a bit flimsy, but you can work around this by putting all `@keyframes` rules at the bottom of any `<style>`.

```astro
<style>
  .my-para {
    color: blue;
  }

  .another-para {
    color: red;
  }

  @keyframes fadeIn {
    to {
      opacity: 100%;
    }
  }
</style>
```

Produces:

```css
.my-para.astro-FNZOVGOV {
  color: #00f;
}
.another-para.astro-FNZOVGOV {
  color: red;
}
@keyframes fadeIn {
  to {
    opacity: 100%;
  }
}
```

## Other @-rules

This seems to be isolated to `@keyframes`. I tested with `@supports` and `@font-face`. Neither of those caused this same, or other, issues.

My hunch is that the extra curly braces needed in `@keyframes` declarations trips things up.

### Link to Minimal Reproducible Example

https://codesandbox.io/s/clever-jennings-xlp4z?file=/src/pages/index.astro
