### ISSUE TITLE
🐛 BUG: css `url()` replaced by __VITE_ASSET__*

### ISSUE THREAD

**Issue by hmvp** [withastro/astro#2146]
### What version of `astro` are you using?

0.21.11

### What package manager are you using?

npm

### What operating system are you using?

Linux on WSL2 (Ubuntu 20.04.3 LTS)

### Describe the Bug

When adding a font from a npm package the font file url in the build is replaced by `__VITE_ASSET__2adefcbc__`

See the linked example. When adding a `@font-face` definition in `global.css` the result in the build is mangled. For the example I could not get the font to actually show on the `astro dev` page. But in my project (which I cannot share) everything works with `astro dev` but building does not. (In the example the actual font file is not copied to the build dir. This does happen in my project)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-eehb2a-fggvjv?devtoolsheight=33&file=dist/assets/index.4daba237.css

**Comment by tusamni** [comment]
Just experienced this as well. Build doesn't include the font file, dev works fine.

**Comment by jonathantneal** [comment]
Confirmed.

```css
@font-face{
  font-family: "FA";
  font-style:normal;
  font-weight:300;
  font-display:swap;
  src: url(__VITE_ASSET__2adefcbc__) format("woff2");
}
```
