### ISSUE TITLE
🐛 BUG: PostCSS example from documentation does not work (and some plugins are broken)

### ISSUE THREAD

**Issue by felixsanz** [withastro/astro#3528]
### What version of `astro` are you using?

v1.0.0-beta.40

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

https://docs.astro.build/en/guides/styling/#postcss

Documentation says that PostCSS integration can be enabled with just creating a `postcss.config.js` file, install some plugins and require them there.

And it works with plugins like `autoprefixer`, but `postcss-nesting` does not work. The example in the documentation uses `postcss-preset-env` (which also includes `postcss-nesting`).

In the test case i created i just forked the "Just the basics" repo example, installed the plugin, added `postcss.config.js` and moved the css inside `components/Card.astro` so it becomes:

```css
	.link-card {
		list-style: none;
		display: flex;
		padding: 0.15rem;
		background-image: var(--link-gradient);
		background-size: 400%;
		border-radius: 0.5rem;
		background-position: 100%;
		transition: background-position 0.6s cubic-bezier(0.22, 1, 0.36, 1);

		& > a {
			width: 100%;
			text-decoration: none;
			line-height: 1.4;
			padding: 1em 1.3em;
			border-radius: 0.35rem;
			color: var(--text-color);
			background-color: white;
			opacity: 0.8;
		}
```

![1654474144](https://user-images.githubusercontent.com/6182099/172076269-eb8f5b54-5228-4bb3-9238-e40f54ec685e.png)

The nesting thing does not work, devtools shows an error because invalid property. In the case of doing this in a svelte component... the dev server crash and doesn't let you continue.

Looks like postcss plugins that include (at the moment) a custom syntax does not work

### Link to Minimal Reproducible Example

https://codesandbox.io/s/silent-dew-fehxqz

### Participation

- [ ] I am willing to submit a pull request for this issue.
