### ISSUE TITLE
Astro hangs on invalid scss

### ISSUE THREAD

**Issue by altano** [withastro/astro#4615]
### What version of `astro` are you using?

1.1.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

linux / stackblitz

### Describe the Bug

Invalid SCSS causes Astro to hang in dev mode. The page will never finish loading. This SCSS (notice the lack of a closing parenthesis) causes the problem:

```scss
<style lang="scss">
	article:global(:is(h1, h2, h3, h4, h5, h6):hover {
		color: purple;
	}
</style>
```

This SCSS is the only thing added to the default Astro demo. Remove it and restart the dev server and the page will load fine.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ebopvr?file=src/components/Card.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.
