### ISSUE TITLE
Fonts are not found after SSR build (when using `public` directory)

### ISSUE THREAD

**Issue by SMEETT** [withastro/astro#4718]
### What version of `astro` are you using?

v1.1.6

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

NPM

### What operating system are you using?

Win 11 Enterprise (10.0.22000 Build 22000)

### Describe the Bug

When fonts sit in `public/fonts` they are moved to `dist/fonts` after build, but Astro (or Vite) expects them at `dist/assets/fonts` — the solution is to move them out of `public/fonts` into `assets/fonts` before building.

So either this is a bug or the current Astro docs are not up to date: 
> If you want to add font files to your project, we recommend adding them to your [public/ directory](https://docs.astro.build/en/core-concepts/project-structure/#public).

https://docs.astro.build/en/guides/fonts/

P.S: Thanks to **happydev** on Discord who was friendly enough to help find the issue <3

### Link to Minimal Reproducible Example

astro.new

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
You can have fonts in public for sure. It's all about how you reference them. As long as you referencing them by absolute path like so:

```css
@font-face {
  font-family: "Open Sans";
  src: url("/fonts/OpenSans-Regular-webfont.woff2") format("woff2"),
       url("/fonts/OpenSans-Regular-webfont.woff") format("woff");
}
```

Then it should work fine. If you are seeing otherwise can you create a stackblitz?
