### ISSUE TITLE
Markdown plugin rehype-autolink-headings does not work with `.md` files

### ISSUE THREAD

**Issue by devgioele** [withastro/astro#5001]
### What version of `astro` are you using?

1.4.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

The Markdown rehype plugin `rehype-autolink-headings` does only work with MDX files, while it should also work with Markdown files.
The attached example shows that heading IDs and links are injected on page `/mdx`, but not on page `/md`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-ofyb1r

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by devgioele** [comment]
After experimenting with the tests of the astro codebase, I understood that the heading IDs that Astro generates automatically are added **after** all plugins are applied. Using `rehype-slug` before `rehype-autolink-headings` solved the issue.

[The documentation explains it actually](https://docs.astro.build/en/guides/markdown-content/#markdown-heading-ids), but it is easy to miss.

**Comment by ryuheechul** [comment]
Few quick tips for (whom found this issue by googling) who's trying to use `rehype-autolink-headings` for the first time like me.

First you will need that `rehyp-slug` thing @devgioele mentioned 👍🏼.

And by default what's added by this plugin is `<a ...><span class="icon icon-link" /></span></a>` which is not visible unless you have CSS configured to render something for `.icon-link` or `.icon`. You might need/want to add `display: inline-block;` (css) or `.inline-block` (tailwind) too.

**Comment by mrchantey** [comment]
An example implementation:

```js
// astro.config.mjs
import rehypeSlug from 'rehype-slug'
import rehypeAutolinkHeadings from 'rehype-autolink-headings'
export default defineConfig({
  markdown: {
    rehypePlugins: [
      rehypeSlug,
      [rehypeAutolinkHeadings, { behavior: 'append' }]
  }
})
```

```css
// style.css
span.icon-link::before {
  content: '#';
  font-size: 0.8em;
  margin-left: 10px;
}
```

**Comment by camball** [comment]
@mrchantey That was a super helpful starting point—thanks. I was able to improve on it slightly for my use case of putting a hash symbol to the left of my headings, fading in when the header is hovered over and fading out when not. I ended up finding a great pure-CSS solution that looks fantastic, give it a try:

```css
span.icon-link::before {
    content: '#';
    position: absolute;
    left: -23px;
    opacity: 0;
    transition: opacity 0.3s ease;
}

h2:hover span.icon-link::before,
h3:hover span.icon-link::before,
h4:hover span.icon-link::before {
    opacity: 1;
}

h2,
h3,
h4 {
    position: relative;
}
```
