### ISSUE TITLE
"Shorter CSS naming algorithm" update causes breaking changes in projects that do not use output hashes

### ISSUE THREAD

**Issue by Enteleform** [withastro/astro#5134]
### What version of `astro` are you using?

1.5.2

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

After upgrading from `1.3.0` to `1.5.2`, I noticed that an issue with missing CSS was introduced in `astro build`.

It seems to be a result of https://github.com/withastro/astro/pull/5036

----

When using this configuration:

```yaml
vite: {
  build: {
    rollupOptions: {
      output: {
        assetFileNames: "assets/[name][extname]",
        entryFileNames: "[name].js",
      }
    }
  }
}
```

the build output with `1.3.0` was:
```
/dist/
  /assets/
    Page_A.css
    Page_A-Page_B.css
    Page_B.css
```

----

The current build output with `1.5.2` is:
```
/dist/
  /assets/
    Page_A.css
    Page_B.css
```

and the following warning is displayed:
```shell
12:27:06 PM [build] Building static entrypoints...
The emitted file "assets/Page_A.css" overwrites a previously emitted file of the same name.
```

### Participation

- [ ] I am willing to submit a pull request for this issue.
