### ISSUE TITLE
The hash of css class names packaged on different platform systems is inconsistent

### ISSUE THREAD

**Issue by J-env** [withastro/astro#5136]
### What version of `astro` are you using?

1.5.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

The hash of the css class name is inconsistent, resulting in a change in the hash of the packaged file.

```astro
// example.astro
<style>
.example { 
  font-size: 34px;
}
</style>
```

Mac output file: [name].f6446fc8.css

```css
.example:where(.astro-6YSHC6AL){font-size:34px}
```

Windows output: [name].12333479.css

```css
.example:where(.astro-CVKMEFR4){font-size:34px}
```

### Link to Minimal Reproducible Example

none

### Participation

- [ ] I am willing to submit a pull request for this issue.
