### ISSUE TITLE
inconsistent CSS behavior in dynamic routes

### ISSUE THREAD

**Issue by Enteleform** [withastro/astro#5251]
```yaml
Astro Version:    1.6.1
SSR Adapter:      No
Package Manager:  NPM
Operating System: Windows
Reproduction:     https://github.com/enteleform-codesandbox/0022--Astro--DynamicRoutes-CSS
```

&nbsp;  
When generating routes dynamically, it seems that there are cases where styles from multiple routes are applied at the same time.

After narrowing it down to a minimal repro, the cause seems to be pages having the same HTML output, but different CSS.

This was also the case in the actual project where I initially ran into the issue: a PDF generator that reuses HTML for multiple routes, with changes to the CSS for different print sizes.

It seems like this could potentially be related to #3816. However, this example is using `import.meta.glob`, while the other issue is using `Astro.glob`.
&nbsp;  

-----

## Different HTML
Styles are applied as expected:

![HTML-Different](https://user-images.githubusercontent.com/10906415/198847113-60abdac1-bb55-4f61-957f-db8656f1f4da.png)

![CSS-Different](https://user-images.githubusercontent.com/10906415/198847110-da2c3fbb-9056-4bd4-bc8a-d8a80cf367cf.png)
&nbsp;  

-----

## Same HTML
Styles from both routes are applied:
![HTML-Same](https://user-images.githubusercontent.com/10906415/198847109-74b572e5-b102-419e-86bd-2c8a36719d9a.png)

![CSS-Same](https://user-images.githubusercontent.com/10906415/198847112-fa2491e2-2fa5-45cf-b7d8-e0b21aeef755.png)
&nbsp;
