### ISSUE TITLE
Astro Node SSR mode does not obey server.host setting within a Docker container

### ISSUE THREAD

**Issue by CM-IV** [withastro/astro#5420]
### What version of `astro` are you using?

1.6.9

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

pnpm

### What operating system are you using?

Ubuntu Linux 22.10

### Describe the Bug

# The Issue I'm Having
I am using the Node adapter for Astro and am trying to use it in conjunction with the PocketBase db.  This is all setup within a docker-compose.yml file here:

```yaml
version: "3.7"
services:
  client:
    environment:
      - NODE_ENV=production
      - PORT=5075
    build:
      dockerfile: Dockerfile
      context: ./
    working_dir: /app
    stdin_open: true
    ports:
      - "5075:5075"
    restart: unless-stopped
    volumes:
      - data:/app

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:0.8.0-rc3
    container_name: pocketbase
    restart: unless-stopped
    #command:
      #- --encryptionEnv #optional
      #- ENCRYPTION #optional
    #environment:
      #ENCRYPTION: example #optional
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/pb_data
      #- /path/to/public:/pb_public #optional

volumes:
  data:
```

The Astro client uses this Dockerfile that is built with docker-compose:

```yaml
FROM node:18-slim

WORKDIR /app

COPY . .

RUN corepack enable

RUN pnpm install

RUN pnpm run build

CMD ["node", "./dist/server/entry.mjs"]
```

This is the astro.config.mjs file that I am using currently:

```js
import { defineConfig } from 'astro/config';
import node from '@astrojs/node';

// https://astro.build/config
export default defineConfig({
    output: 'server',
    adapter: node({
        mode: 'standalone'
    }),
    server: { 
        port: 5075,
        host: "0.0.0.0"
    }
});

```

The problem arrives whenever I try to run the built server entry file with node within the docker container, which is shown here:

![image](https://user-images.githubusercontent.com/44551614/202255396-042fd61e-5877-45f1-bf2c-b79043aab53a.png)

I'd like the Astro server to listen on the `0.0.0.0` host address that I have configured within the `astro.config.mjs` file, but it doesn't seem to be working.

# What I've Tried So Far
I have run the built server outside of the docker container and I do not have an issue here, using `pnpm run build` and then `node ./dist/server/entry.mjs` - which can be seen here:

![image](https://user-images.githubusercontent.com/44551614/202256240-e155abdb-e96d-4153-9f91-85ff2bbb56af.png)

I have also tried to use the server.host = true option within the Dockerfile only to get the same result.

I do not believe this to be an issue with how I have setup my docker container, but if it is let me know.

I will link to the GitHub repository so that it can be cloned.

### Link to Minimal Reproducible Example

https://github.com/CM-IV/astro-fast-dash.git

### Participation

- [ ] I am willing to submit a pull request for this issue.
