### ISSUE TITLE
pseudo class and pseudo element only selectors break scoped styles

### ISSUE THREAD

**Issue by kagankan** [withastro/astro#5795]
### What version of `astro` are you using?

1.9.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows 11

## Current behavior

```astro
<a href=""></a>

<style>
  :any-link::after {
    content: "link";
  }
</style>
```

The style is converted to the CSS below:

```css
:any-link:after:where(.astro-RJEN7MQD){content:"link"}
```

The style is not applied to the `a` element.

## Expected behavior

```css
:any-link:where(.astro-RJEN7MQD):after{content:"link"}
/* or */
:where(.astro-RJEN7MQD):any-link:after{content:"link"}
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-bqgpy9?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.
