### ISSUE TITLE
Imported CSS getting duplicated in dev server

### ISSUE THREAD

**Issue by mayank99** [withastro/astro#5857]
### What version of `astro` are you using?

1.9.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows / Stackblitz

### Describe the Bug

<details>

<summary>Original description</summary>

When importing a css file (local or npm. `@import` or `import`. doesn't matter), the styles get duplicated anywhere from 2-4 times.

<img width="313" alt="" src="https://user-images.githubusercontent.com/9084735/212418935-0bcc00f8-8f92-4581-a940-0f6446dc160d.png">

Doesn't seem to affect prod build, and doesn't seem to affect styles defined in the same file.

Possibly related issues: #5817, #5834, #5715

</details>

When importing a stylesheet into a cascade layer, the styles get incorrectly duplicated outside the layer. See comment below: https://github.com/withastro/astro/issues/5857#issuecomment-1401158209

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-fkhp2c-kkhdqq

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mayank99** [comment]
update: when using cascade layers, the problem becomes much more serious than just an annoyance. the duplicated css is getting applied _without_ `@layer`.

small example:

```scss
// in styles.css
body {
  background: tomato;
}
```

```scss
@layer A, B; // define layers up front

@import '../styles.css' layer (A);

@layer B {
  :where(body) {
    background: hotpink;
  }
}
```

with that layered setup, `hotpink` should get applied, but instead `tomato` gets applied.

repro: https://stackblitz.com/edit/github-fkhp2c-ayy2wb?file=src%2Fpages%2Findex.astro,src%2Fstyles.css

**Comment by natemoo-re** [comment]
The original issue here is fixed by https://github.com/withastro/astro/pull/5917.

The `@layer` bug seems like an upstream Vite issue.

**Comment by mayank99** [comment]
just for clarity, i did not touch the `devSourcemaps` option. maybe another e2e fixture without that option would help?

i can open an issue in vite for the layer issue, but i can't seem to reproduce it in vanilla vite

**Comment by gvkhna** [comment]
O yes, that makes sense. Astro is doing the same thing irrespective of devSourcemaps I believe. But the issue would be fixed without double styles. That makes sense why you can’t reproduce in vanilla vite. I’m pretty sure it’s the same issue but I would have to take a closer look when this PR is merged, can you try with the PR?

**Comment by natemoo-re** [comment]
> just for clarity, i did not touch the `devSourcemaps` option. maybe another e2e fixture without that option would help?

Yep, I will add another test to confirm that your first repro doesn't regress.

> i can open an issue in vite for the layer issue, but i can't seem to reproduce it in vanilla vite

For this one, I'm seeing some strange output that leads me to believe this is an upstream issue... But I suppose it's possible there's something happening on our end? I'll have to look into this more if you can't repro in plain Vite.

```css
@layer A, B;
@media (A){
		@layer vite--anon-layer-4076b8fe-0{
body {
  font-family: system-ui;
  display: grid;
  place-items: center;
  background-color: tomato;
}
		}
}
@layer B {
		:where(body) {
			background-color: hotpink;
		}
	}
```
