### ISSUE TITLE
@astro/tailwind is not adding prefixes in devmode

### ISSUE THREAD

**Issue by royeden** [withastro/astro#5989]
### What version of `astro` are you using?

2.0.1

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

When updating to Astro 2.0 and the latest `@astro/tailwind` integration, vendor prefixes are no longer being added to classes when the dev server is running.

To specify:

```html
<h1 class="bg-clip-text text-transparent bg-gradient-to-r from-cyan-500 to-blue-500">Test</h1>
```

poduces the following `<style>` injected into astro by vite:

```css
.bg-clip-text {
  background-clip: text;
}
```

instead of the expected:

```css
.bg-clip-text {
  -webkit-background-clip: text;
  background-clip: text;
}
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-hbvmrj

### Participation

- [x] I am willing to submit a pull request for this issue.
