### ISSUE TITLE
Font family in imported CSS file is wrongly compiled

### ISSUE THREAD

**Issue by zhangzheheng12345** [withastro/astro#6300]
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

npm

### What operating system are you using?

Linux & Windows

### Describe the Bug

This issue happens in a Stylus file, but I think the problem is in Astro, as I even use literal CSS code in Stylus which will insert original CSS, but the behavior is still not correct (in playground of Stylus is actually in expectation).

Reproduce:

```styl
/* Stylus */
*
  font-family: "Roboto Mono", monospace
/* Or
Thus won't be processed by Stylus */
@css {
  * {
    font-family: "Roboto Mono", monospace;
  }
}
```

Expected output:

```css
/* Stylus compiler gives this correctly */
* {
  font-family: "Roboto Mono", monospace;
}
```

However in browser I got this:

```css
/* Integrated with Astro */
* {
  font-family: Roboto Mono, monospace;
}
```
