### ISSUE TITLE
MDX and rehype-mathjax not rendering properly

### ISSUE THREAD

**Issue by ewzpack** [withastro/astro#6404]
### What version of `astro` are you using?

2.0.16

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

rehype-mathjax (CHTML) creates html structure and inject CSS, but the problem is that the CSS gets escaped

for example

```css
mjx-container[jax=&quot;CHTML&quot;] {
  line-height: 0;
}
mjx-stretchy-v &gt; mjx-beg {
  height: 0;
}
```

instead of 

```css
mjx-container[jax="CHTML"] {
  line-height: 0;
}
mjx-stretchy-v > mjx-beg {
  height: 0;
}
```

Its works correctly when using markdown only or importing a `.md` file (containing math expression) into a `.mdx` file.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-r1w9pn?file=src/content/blog/math.mdx

### Participation

- [ ] I am willing to submit a pull request for this issue.
