### ISSUE TITLE
[Netlify] poor support for Netlify's headers config

### ISSUE THREAD

**Issue by jamesarosen** [withastro/astro#6510]
### What version of `astro` are you using?

2.1.3

### Are you using an SSR adapter? If so, which one?

netlify

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

All

### Goal

I want to set long-lived `cache-control` headers on fingerprinted static assets to improve my site performance.

### What I tried

Based on Netlify's [custom header docs](https://docs.netlify.com/routing/headers/), I added this to my `netlify.toml`:

```toml
[[headers]]
  for = "/_astro/*.:fingerprint.:ext"
  [headers.values]
  cache-control = '''
  public,
  max-age=86400,
  stale-while-revalidate=2592000,
  stale-if-error=2592000,
  immutable'''
```

but Netlify didn't pick up the headers. I tried switching from `netlify.toml` to `_headers`:

```headers
# Static assets with fingerprints
/_astro/*.:fingerprint.:ext
  cache-control: public
  cache-control: max-age=86400
  cache-control: stale-while-revalidate=2592000
  cache-control: stale-if-error=2592000
  cache-control: immutable
```

but Netlify _still_ didn't pick up the headers.

Eventually, I realized that Netlify needs the `_headers` file to appear in `dist/` alongside `_redirects`. This worked:

```json
// package.json
"scripts": {
  "build": "pnpm run build:astro && pnpm run build:netlify",
  "build:astro": "astro build",
  "build:netlify": "cp _headers dist/"
}
```

### Request

1. the `@astrojs/netlify` adapter copy `_headers` to `dist/` automatically
2. the default astro-netlify template includes a `_headers` file with comments about how to use it

I'm happy to help if folks think this is a good idea.

### Link to Minimal Reproducible Example

n/a

### Participation

- [X] I am willing to submit a pull request for this issue.
