### ISSUE TITLE
VERCEL_ANALYTICS_ID not found

### ISSUE THREAD

**Issue by pijusz** [withastro/astro#7573]
### What version of `astro` are you using?

2.7.4

### Are you using an SSR adapter? If so, which one?

Vercel/Hybrid

### What package manager are you using?

yarn

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

```json
 "dependencies": {
    "@astrojs/vercel": "^3.6.0",
    "astro": "^2.7.4"
  }
```
config: 
```javascript
import vercel from "@astrojs/vercel/static";
import { defineConfig } from "astro/config";

export default defineConfig({
  output: "static",
  adapter: vercel({
    analytics: true,
  }),
});
```

built script excerpt:
```javascript
  const e = {}.PUBLIC_VERCEL_ANALYTICS_ID;
  if (!e) {
    console.error("[Analytics] VERCEL_ANALYTICS_ID not found");
    return;
  }
```

Once loading any website, there is console error "[Analytics] VERCEL_ANALYTICS_ID not found".

I've tried: different builds (static, hybrid, server)

### What's the expected result?

There is no console error, and website reports to Vercel web vitals.

### Link to Minimal Reproducible Example

https://molecular-sphere.vercel.app/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
There is definitely a history of this being an issue, perhaps there was a regression somewhere! Thanks for reporting.

https://github.com/withastro/astro/pull/6751

**Comment by pijusz** [comment]
I've already sent the deployed example

General things:
Plain Vercel/Astro deployment from github repo
Analytics enabled on vercel, added config

**Comment by pijusz** [comment]
Adding the repo: https://github.com/pijusz/molecular-sphere

**Comment by pijusz** [comment]
Any progress on this one?
I could try fixing it myself, but would need some ideas where I should even start.

**Comment by bluwy** [comment]
When I run the repro with `VERCEL_ANALYTICS_ID=foobar pnpm build`, I can see that it's being properly replaced. I guess my other hunch is that Vercel "intelligently" passes `PUBLIC_VERCEL_ANALYTICS_ID` instead because it knows we're using Astro. Could you help test this out by adding this in `astro.config.mjs` and deploying to Vercel?

```js
console.log(process.env.VERCEL_ANALYTICS_ID, process.env.PUBLIC_VERCEL_ANALYTICS_ID)
if (!process.env.VERCEL_ANALYTICS_ID) {
 process.env.VERCEL_ANALYTICS_ID = process.env.PUBLIC_VERCEL_ANALYTICS_ID
}
```

**Comment by pijusz** [comment]
Doesn't seem like fixed. If you do the build, the whole function that consumes the environment variable doesn't appear.
![image](https://github.com/withastro/astro/assets/20190386/5a9c8b04-3aa3-4141-8ba0-e9ebe943bd2c)

**Comment by pijusz** [comment]
Vercel Analytics is behind on whole minor version (0.x.x : 0.1.x). Quite possible, that just updating it might work.

**Comment by natemoo-re** [comment]
> Vercel Analytics is behind on whole minor version (0.x.x : 0.1.x). Quite possible, that just updating it might work.

I would expect this to help! We are a bit behind on dependency updates, so we'll try to give this a try

**Comment by Aarekaz** [comment]
![image](https://github.com/withastro/astro/assets/36888347/485434a1-e60a-4940-a208-a41d03ac404d)
I am still not able to use it, Its giving me the same issue. Any fix?

**Comment by Mrahmani71** [comment]
Try this @Aarekaz 
```
define: {
	"import.meta.env.VITE_VERCEL_ANALYTICS_ID": JSON.stringify(process.env.VERCEL_ANALYTICS_ID),
	"import.meta.env.PUBLIC_VERCEL_ANALYTICS_ID": JSON.stringify(process.env.VERCEL_ANALYTICS_ID),
},
```

**Comment by ingomc** [comment]
Whats the progress here, i have Astro 3.2.3 setup, but exactly this error

**Comment by jacobthesheep** [comment]
> Maybe #8021 would help address this, which noted:
> 
> > It also threw an error when only Web Analytics was enabled since the environment variable for Speed Insights VERCEL_ANALYTICS_ID was not available.
> 
> The two features could be causing the confusion

I thought @astrojs/vercel 5.0 fixed this

**Comment by ref-thomasledoux1** [comment]
FWIW, the comment from @bluwy fixed it for me.
Add this to your astro.config.ts:
```
console.log(
  process.env.VERCEL_ANALYTICS_ID,
  process.env.PUBLIC_VERCEL_ANALYTICS_ID,
);
if (!process.env.VERCEL_ANALYTICS_ID) {
  process.env.VERCEL_ANALYTICS_ID = process.env.PUBLIC_VERCEL_ANALYTICS_ID;
}
```

My full astro.config.ts: 
```
import { defineConfig } from "astro/config";
import tailwind from "@astrojs/tailwind";
import mdx from "@astrojs/mdx";
import { remarkReadingTime } from "./src/utils/calculate-reading-time.js";
import vercel from "@astrojs/vercel/serverless";
import react from "@astrojs/react";
import AutoImport from "astro-auto-import";
import {
  astroCodeSnippets,
  codeSnippetAutoImport,
} from "./integrations/astro-code-snippets";
import partytown from "@astrojs/partytown";

// https://astro.build/config
export default defineConfig({
  integrations: [
    tailwind({
      applyBaseStyles: false,
    }),
    react(),
    AutoImport({
      imports: [codeSnippetAutoImport],
    }),
    astroCodeSnippets(),
    partytown({
      config: {
        forward: ["dataLayer.push"],
      },
    }),
    mdx(),
  ],
  vite: {
    define: {
      "process.env.NODE_ENV": `'${process.env.NODE_ENV}'`,
    },
  },
  prefetch: {
    prefetchAll: true,
  },
  output: "hybrid",
  adapter: vercel({
    speedInsights: { enabled: true },
  }),
  markdown: {
    remarkPlugins: [remarkReadingTime],
  },
  site: "https://www.thomasledoux.be",
});

console.log(
  process.env.VERCEL_ANALYTICS_ID,
  process.env.PUBLIC_VERCEL_ANALYTICS_ID,
);
if (!process.env.VERCEL_ANALYTICS_ID) {
  process.env.VERCEL_ANALYTICS_ID = process.env.PUBLIC_VERCEL_ANALYTICS_ID;
}
```
Package versions: 
Astro version: 3.5.5
@astrojs/vercel: 5.2.0

**Comment by kamontat** [comment]
I found the problem why on my cases VERCEL_ANALYTICS_ID doesn't get correctly.

## Current set up

I use GitHub Action to build package and publish package to Vercel for deployment using `vercel cli`. So my GitHub action will be something like below:

```yaml
name: Deployment

on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
      - name: Set up nodejs
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "pnpm"
      - name: Pull environment information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build artifacts
        run: pnpm build
      - name: Deploy artifacts
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
```

However, this doesn't works because `vercel pull` command doesn't pull `VERCEL_ANALYTICS_ID` variable.

> vc pull does not pull VERCEL_ANALYTICS_ID as the Vercel Analytics ID environment variable is inlined during the build process. It is not part of your project Environment Variables, which can be pulled locally using Vercel CLI.
ref: https://vercel.com/docs/speed-insights/api
