### ISSUE TITLE
Resolving Assets in CSS via url()

### ISSUE THREAD

**Issue by KingPr0o7** [withastro/astro#9633]
### Astro Info

```block
Astro                    v4.1.1
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

Doesn't seem to apply. 

### Describe the Bug

When trying to use images in CSS, I can't get the image to load with paths like `@images/`, `../images/` or `/src/images/`. I'm limited to using images in the `public/` directory where the images aren't processed and optimized like into the `webp` format. Images will be not found (404) in my console in **and/or** development/production:
![why](https://github.com/withastro/astro/assets/64029396/4bcfe641-fe62-4df8-8e42-a78d7046702b)

**Note:** I could just be me not understanding the proper implementation, but from the [Discord support thread](https://discord.com/channels/830184174198718474/1193059133520355358), it seems I'm not the only one confused.

### What's the expected result?

It should be a straightforward way to resolve images and use them in CSS. Like simply putting:

```css
@keyframes image-change {
	25% {background-image: url('@images/cat2.png');} 
	75% {background-image: url('@images/cat3.png');}
	100% {background-image: url('@images/cat1.png');}
}
```

or other ways like using `define:vars`:
```css
<style define:vars={{ Cat1, Cat2, Cat3 }}>
@keyframes image-change {
	25% {background-image: var(--Cat2);} 
	75% {background-image: var(--Cat3);}
	100% {background-image: var(--Cat1);}
}
</style>
```

With these, then the images should automatically be processed and URLs resolved and replaced so they show up as an optimized image in **both** production and development. 

### Link to Minimal Reproducible Example

https://stackblitz.com/~/github.com/KingPr0o7/sandbox

### Participation

- [ ] I am willing to submit a pull request for this issue.
