### ISSUE TITLE
When I write the max + calc expression in the less file, it becomes 0 after compilation.

### ISSUE THREAD

**Issue by iamyunsin** [withastro/astro#9903]
### Astro Info

```block
➜  blog git:(main) ✗ pnpm dev

> blog@0.0.1 dev /Users/bullub/个人中心/项目/blog
> astro dev


 astro  v4.2.6 ready in 935 ms

┃ Local    http://localhost:4321/
┃ Network  use --host to expose

20:54:16 watching for file changes...
```

### Describe the Bug

styles/global.less: 
```less
.backtop {
  position: fixed;
  right: max(calc((100vw - 1024px) / 2 - 48px), 0px);
  bottom: 40px; cursor: pointer;
  color:rgba(var(--gray), 40%);

  &:hover {
    color:rgba(var(--gray), 90%);
  }
}
```
The `right: max(calc((100vw - 1024px) / 2 - 48px), 0px);` in this code will be compiled into `right:0`.

### What's the expected result?

The `right: max(calc((100vw - 1024px) / 2 - 48px), 0px);` in this code will be compiled into `right: max(calc((100vw - 1024px) / 2 - 48px), 0px);`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-m24vbx?file=src%2Fstyles%2Fglobal.less

### Participation

- [ ] I am willing to submit a pull request for this issue.
